on:
  workflow_call:

jobs:
  validate_config_filenames:
    name: Config filenames
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate config filenames
        run: python scripts/validate_config_filenames.py
